In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.semi_supervised import LabelPropagation
import numpy as np
ubah=0
confi=1
lb_confi=0.7


# Load iris dataset
iris = load_iris()
X_labeled, X_unlabeled, y_labeled, _ = train_test_split(iris.data, iris.target, test_size=0.5, stratify=iris.target)

# Create initial classifiers
clf1 = RandomForestClassifier()
clf2 = RandomForestClassifier()

# Train initial classifiers on labeled data
clf1.fit(X_labeled, y_labeled)
clf2.fit(X_labeled, y_labeled)

# Start co-training process
for i in range(100):  # Number of iterations
    try:
        
        if len(X_unlabeled)==0:
            break
        
        
        if ubah>10:
                break
        if ubah == 3:
            confi = confi - 0.05
            ubah=0
        if confi <= lb_confi:
                confi = lb_confi
                
                
        # Predict labels for unlabeled data
        print(i)
        pred1 = clf1.predict(X_unlabeled)
        pred2 = clf2.predict(X_unlabeled)

        # Select most confident predictions
        confidence1 = np.max(clf1.predict_proba(X_unlabeled), axis=1)
        confidence2 = np.max(clf2.predict_proba(X_unlabeled), axis=1)
        high_confidence_indices1 = np.where(confidence1 >= confi)[0]
        high_confidence_indices2 = np.where(confidence2 >= confi)[0]
        selected_indices = np.intersect1d(high_confidence_indices1, high_confidence_indices2)
        print(len(selected_indices), len(X_unlabeled))
        print('confi==>>>>',confi)
        
        

        

        if len(selected_indices) > 0:
            # Predictions made by both classifiers for the selected instances
            pred1_selected = pred1[selected_indices]
            pred2_selected = pred2[selected_indices]

            # Check if predictions made by both classifiers are the same
            same_predictions_indices = np.where(pred1_selected == pred2_selected)[0]
            print(pred1_selected)
            print(pred2_selected)

            # Add instances with same predictions to the labeled data
            if len(same_predictions_indices) > 0:
                X_labeled = np.vstack((X_labeled, X_unlabeled[selected_indices[same_predictions_indices]]))
                y_labeled = np.hstack((y_labeled, pred1[selected_indices[same_predictions_indices]]))

                # Remove added instances from the unlabeled data
                X_unlabeled = np.delete(X_unlabeled, selected_indices[same_predictions_indices], axis=0)
        else:
            print(0)

        
            
            if len(selected_indices) > 0:
                print('ubah')
                X_labeled = np.vstack((X_labeled, X_unlabeled[selected_indices]))
                y_labeled = np.hstack((y_labeled, pred1[selected_indices]))  # or use pred2

                X_unlabeled = np.delete(X_unlabeled, selected_indices, axis=0)
        if len(selected_indices) == 0:
            ubah = ubah + 1
        else:
            ubah = 0
        print(ubah)
        print()

        # Train classifiers on expanded labeled data
        clf1.fit(X_labeled, y_labeled)
        clf2.fit(X_labeled, y_labeled)
    except Exception as e:
        print("Error occurred:", e)
        break
        # Return error or handle it accordingly

    


# Evaluate performance on test set
X_test, y_test = iris.data, iris.target
accuracy1 = clf1.score(X_test, y_test)
accuracy2 = clf2.score(X_test, y_test)
print("Classifier 1 accuracy:", accuracy1)
print("Classifier 2 accuracy:", accuracy2)
print(len(X_unlabeled))

0
36 75
confi==>>>> 1
[0 2 2 2 0 0 0 0 2 0 0 1 0 2 0 2 0 2 0 2 2 2 2 1 0 0 2 2 1 0 1 2 0 0 1 0]
[0 2 2 2 0 0 0 0 2 0 0 1 0 2 0 2 0 2 0 2 2 2 2 1 0 0 2 2 1 0 1 2 0 0 1 0]
0

1
4 39
confi==>>>> 1
[2 1 2 1]
[2 1 2 1]
0

2
3 35
confi==>>>> 1
[1 1 2]
[1 1 2]
0

3
1 32
confi==>>>> 1
[1]
[1]
0

4
1 31
confi==>>>> 1
[2]
[2]
0

5
0 30
confi==>>>> 1
0
1

6
2 30
confi==>>>> 1
[1 1]
[1 1]
0

7
0 28
confi==>>>> 1
0
1

8
0 28
confi==>>>> 1
0
2

9
1 28
confi==>>>> 1
[2]
[2]
0

10
1 27
confi==>>>> 1
[1]
[1]
0

11
0 26
confi==>>>> 1
0
1

12
0 26
confi==>>>> 1
0
2

13
0 26
confi==>>>> 1
0
3

14
17 26
confi==>>>> 0.95
[0 0 1 2 2 0 0 1 0 0 1 2 1 0 1 2 1]
[0 0 1 2 2 0 0 1 0 0 1 2 1 0 1 2 1]
0

15
1 9
confi==>>>> 0.95
[1]
[1]
0

16
0 8
confi==>>>> 0.95
0
1

17
0 8
confi==>>>> 0.95
0
2

18
0 8
confi==>>>> 0.95
0
3

19
3 8
confi==>>>> 0.8999999999999999
[1 1 0]
[1 1 0]
0

20
1 5
confi==>>>> 0.8999999999999999
[1]
[1]
0

21
0 4
confi==>>>> 0.8999999999999999
0
1

22
0 4
confi==>>>> 0.8999999999999999
0
2

23
0